React.js Capstone project
m00h0/JS-react-capstone pull request #3
Opened 2023-10-11 19:02 UTC by newtonah0

I made These requirements
API First you need to choose an API to base the development of the webapp on. The API should allow you to get numeric values based on a parameter. We recommend that you choose an API that is open or needs an API key. If you choose an API that require authentication, you should implement it on your own.

Some example APIs are:

Financial modeling prep API: stock data.
Air pollution API: air quality data.
You can find many APIs in this GitHub repo. Some of the APIs requires a token for authentication and some others are just open.

Design

You should follow these design guidelines, including:
Colors (select one main color for your website).
Typography: font face, size and weight.
Layout: composition and space between elements.
Original design idea by Nelson Sakwa on Behance.

The Creative Commons license of the design requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

Interactions

Home page

When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
Along with the category name, you will display some numeric values per category that come from the API.
When the user clicks (or taps) on a category item, the application navigates to the details page.
Details page

In the details page, the webapp retrieves data from the API to show detailed data in the category.
When the user clicks on the "Back" button (<), the user navigates to the home page.
Testing requirements

Create integration tests for your application using the React Testing Library.
You may need to mock the access to the API, so that your tests don't send actual requests.
You may need to mock the connection to the Redux Store.

The project is a single-page application (SPA) built with React and Redux.
The data retrieved from the API should be stored in the Redux store.
You should filter the data that you retrieve from the API using a Filter stateless component.
Every page (the main page and the pages for each item) should have a unique route within the SPA.
The project should be deployed and accessible online using [Render](https://render.com/), [Netlify](https://www.netlify.com/) or [GitHub Pages](https://pages.github.com/).
Add a link to the online version of your app to your README file.

2023-10-11 22:13 UTC, levy002 requested changes
## Hello @newtonah0   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 22:13 UTC, levy002 commented on README.md
> +- ✅ Click [here](https://www.loom.com/share/6dbe062e1e3a48b3a8528eaf1d9ff15f?sid=7dae9335-f57e-478b-859a-b2b325fe266a) to see the video presentation.
- [x] As you work on your presentation video, consider featuring a code snippet that you find particularly intriguing or that you're proud of creating. This will not only provide a concrete demonstration of your technical skills but also make your presentation more engaging. Select the part of the code that best reflects your unique contributions or the most challenging problem you've solved. By highlighting this code, you can effectively convey your passion for the project and your commitment to its success, making a strong and memorable impression on your audience.

2023-10-11 22:13 UTC, levy002 commented on src/components/fruitCategories/fruitCategories.css
> +}
- [x] To match the provided mobile designs, it's essential to ensure that the fruit cards fit perfectly on the screen without any horizontal scrolling. I'd recommend making some adjustments to your layout to achieve this. You can try resizing the fruit cards or modifying the layout to create a user-friendly and seamless mobile experience. This small tweak will make a big difference in the visual appeal and usability of your mobile design. Keep up the great work, and your project will shine even brighter!


   ### YOUR DESIGN
  ![chrome-capture-2023-9-11](https://github.com/newtonah0/JS-react-capstone/assets/87197412/6254f82d-e436-46db-8b84-7b8e3d34468f)

   ### PROVIDED DESIGN
   ![image](https://github.com/newtonah0/JS-react-capstone/assets/87197412/d4081c8b-a4a6-4221-a1b5-601aabd0c453)

2023-10-11 22:13 UTC, levy002 commented on src/components/header/header.css
> +}
- [ ] To ensure your header content matches the provided mobile designs, consider adjusting the font size. Making the text slightly smaller will enhance visibility and alignment with the design you're aiming for. This simple tweak will help your header stand out and provide a more polished, user-friendly look on mobile devices. Keep up the good work!

  ### YOUR DESIGN
  ![image](https://github.com/newtonah0/JS-react-capstone/assets/87197412/cf5a135e-47d4-48ef-9b39-cb57c43e6d8d)

  ### PROVIDED DESIGN
  ![image](https://github.com/newtonah0/JS-react-capstone/assets/87197412/03f7ce21-f256-4ab2-9869-e22c755ffbf5)

2023-10-12 10:55 UTC, newtonah0 commented on README.md
> +- ✅ Click [here](https://www.loom.com/share/6dbe062e1e3a48b3a8528eaf1d9ff15f?sid=7dae9335-f57e-478b-859a-b2b325fe266a) to see the video presentation.
Thank you @levy002 I will do that 👍.

2023-10-12 13:52 UTC, prolajumokeoni approved these changes
Hi @newtonah0 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Header is aligned 👏🏿 
- Horizontal scroll is fixed  ✅ 
  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- In your presentation video it would be nice to highlight a piece of code you find interesting 👍🏿 
- [Branch name](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects) should have a name of a feature or action related to your project 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 15:56 UTC, merged